#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x5D2EEE6F6F349D7C (tim@centricular.com)
#
Name     : gst-plugins-good
Version  : 1.20.3
Release  : 76
URL      : https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.20.3.tar.xz
Source0  : https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.20.3.tar.xz
Source1  : https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.20.3.tar.xz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause LGPL-2.1 MIT
Requires: gst-plugins-good-data = %{version}-%{release}
Requires: gst-plugins-good-filemap = %{version}-%{release}
Requires: gst-plugins-good-lib = %{version}-%{release}
Requires: gst-plugins-good-license = %{version}-%{release}
Requires: gst-plugins-good-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : buildreq-meson
BuildRequires : buildreq-qmake
BuildRequires : bzip2-dev
BuildRequires : gdk-pixbuf
BuildRequires : glu-dev
BuildRequires : gstreamer-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libsoup-dev
BuildRequires : mesa-dev
BuildRequires : mpg123-dev
BuildRequires : nasm-bin
BuildRequires : orc-dev
BuildRequires : pkgconfig(cairo-gobject)
BuildRequires : pkgconfig(flac)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gstreamer-plugins-base-1.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(libsoup-3.0)
BuildRequires : pkgconfig(taglib)
BuildRequires : pkgconfig(valgrind)
BuildRequires : pkgconfig(vpx)
BuildRequires : qtbase-extras
BuildRequires : speex-dev
BuildRequires : v4l-utils-dev
BuildRequires : valgrind
BuildRequires : wavpack-dev

%description
v4l2 plugins
============
The idea is a bit the same as the idea for the v4l1 plugins. We want
one generic v4l2element, and a few child objects (probably only two:
v4l2src and v4l2sink):

%package data
Summary: data components for the gst-plugins-good package.
Group: Data

%description data
data components for the gst-plugins-good package.


%package extras
Summary: extras components for the gst-plugins-good package.
Group: Default

%description extras
extras components for the gst-plugins-good package.


%package filemap
Summary: filemap components for the gst-plugins-good package.
Group: Default

%description filemap
filemap components for the gst-plugins-good package.


%package lib
Summary: lib components for the gst-plugins-good package.
Group: Libraries
Requires: gst-plugins-good-data = %{version}-%{release}
Requires: gst-plugins-good-license = %{version}-%{release}
Requires: gst-plugins-good-filemap = %{version}-%{release}

%description lib
lib components for the gst-plugins-good package.


%package license
Summary: license components for the gst-plugins-good package.
Group: Default

%description license
license components for the gst-plugins-good package.


%package locales
Summary: locales components for the gst-plugins-good package.
Group: Default

%description locales
locales components for the gst-plugins-good package.


%prep
%setup -q -n gst-plugins-good-1.20.3
cd %{_builddir}/gst-plugins-good-1.20.3
pushd ..
cp -a gst-plugins-good-1.20.3 buildavx2
popd
pushd ..
cp -a gst-plugins-good-1.20.3 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656120941
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dv4l2-gudev=disabled  builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -O3" CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dv4l2-gudev=disabled  builddiravx2
ninja -v -C builddiravx2
CFLAGS="$CFLAGS -m64 -march=x86-64-v4 -Wl,-z,x86-64-v4 -O3" CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v4 -Wl,-z,x86-64-v4 " LDFLAGS="$LDFLAGS -m64 -march=x86-64-v4" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dv4l2-gudev=disabled  builddiravx512
ninja -v -C builddiravx512

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gst-plugins-good
cp %{_builddir}/gst-plugins-good-1.20.3/COPYING %{buildroot}/usr/share/package-licenses/gst-plugins-good/545f380fb332eb41236596500913ff8d582e3ead
cp %{_builddir}/gst-plugins-good-1.20.3/gst/rtp/dboolhuff.LICENSE %{buildroot}/usr/share/package-licenses/gst-plugins-good/057705e31a95ff560d92f8abc2e62d2894fba796
cp %{_builddir}/gst-plugins-good-1.20.3/gst/rtsp/COPYING.MIT %{buildroot}/usr/share/package-licenses/gst-plugins-good/f6e583b41a8e91303bf19c8b17c0086872de5977
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot}-v4 ninja -C builddiravx512 install
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gst-plugins-good-1.0
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/gstreamer-1.0/presets/GstIirEqualizer10Bands.prs
/usr/share/gstreamer-1.0/presets/GstIirEqualizer3Bands.prs
/usr/share/gstreamer-1.0/presets/GstQTMux.prs
/usr/share/gstreamer-1.0/presets/GstVP8Enc.prs

%files extras
%defattr(-,root,root,-)
/usr/lib64/gstreamer-1.0/libgstqmlgl.so

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-gst-plugins-good

%files lib
%defattr(-,root,root,-)
/usr/lib64/gstreamer-1.0/libgstalaw.so
/usr/lib64/gstreamer-1.0/libgstalpha.so
/usr/lib64/gstreamer-1.0/libgstalphacolor.so
/usr/lib64/gstreamer-1.0/libgstapetag.so
/usr/lib64/gstreamer-1.0/libgstaudiofx.so
/usr/lib64/gstreamer-1.0/libgstaudioparsers.so
/usr/lib64/gstreamer-1.0/libgstauparse.so
/usr/lib64/gstreamer-1.0/libgstautodetect.so
/usr/lib64/gstreamer-1.0/libgstavi.so
/usr/lib64/gstreamer-1.0/libgstcairo.so
/usr/lib64/gstreamer-1.0/libgstcutter.so
/usr/lib64/gstreamer-1.0/libgstdebug.so
/usr/lib64/gstreamer-1.0/libgstdeinterlace.so
/usr/lib64/gstreamer-1.0/libgstdtmf.so
/usr/lib64/gstreamer-1.0/libgsteffectv.so
/usr/lib64/gstreamer-1.0/libgstequalizer.so
/usr/lib64/gstreamer-1.0/libgstflac.so
/usr/lib64/gstreamer-1.0/libgstflv.so
/usr/lib64/gstreamer-1.0/libgstflxdec.so
/usr/lib64/gstreamer-1.0/libgstgdkpixbuf.so
/usr/lib64/gstreamer-1.0/libgstgoom.so
/usr/lib64/gstreamer-1.0/libgstgoom2k1.so
/usr/lib64/gstreamer-1.0/libgstgtk.so
/usr/lib64/gstreamer-1.0/libgsticydemux.so
/usr/lib64/gstreamer-1.0/libgstid3demux.so
/usr/lib64/gstreamer-1.0/libgstimagefreeze.so
/usr/lib64/gstreamer-1.0/libgstinterleave.so
/usr/lib64/gstreamer-1.0/libgstisomp4.so
/usr/lib64/gstreamer-1.0/libgstjpeg.so
/usr/lib64/gstreamer-1.0/libgstlevel.so
/usr/lib64/gstreamer-1.0/libgstmatroska.so
/usr/lib64/gstreamer-1.0/libgstmonoscope.so
/usr/lib64/gstreamer-1.0/libgstmpg123.so
/usr/lib64/gstreamer-1.0/libgstmulaw.so
/usr/lib64/gstreamer-1.0/libgstmultifile.so
/usr/lib64/gstreamer-1.0/libgstmultipart.so
/usr/lib64/gstreamer-1.0/libgstnavigationtest.so
/usr/lib64/gstreamer-1.0/libgstoss4.so
/usr/lib64/gstreamer-1.0/libgstossaudio.so
/usr/lib64/gstreamer-1.0/libgstpng.so
/usr/lib64/gstreamer-1.0/libgstpulseaudio.so
/usr/lib64/gstreamer-1.0/libgstreplaygain.so
/usr/lib64/gstreamer-1.0/libgstrtp.so
/usr/lib64/gstreamer-1.0/libgstrtpmanager.so
/usr/lib64/gstreamer-1.0/libgstrtsp.so
/usr/lib64/gstreamer-1.0/libgstshapewipe.so
/usr/lib64/gstreamer-1.0/libgstsmpte.so
/usr/lib64/gstreamer-1.0/libgstsoup.so
/usr/lib64/gstreamer-1.0/libgstspectrum.so
/usr/lib64/gstreamer-1.0/libgstspeex.so
/usr/lib64/gstreamer-1.0/libgsttaglib.so
/usr/lib64/gstreamer-1.0/libgstudp.so
/usr/lib64/gstreamer-1.0/libgstvideo4linux2.so
/usr/lib64/gstreamer-1.0/libgstvideobox.so
/usr/lib64/gstreamer-1.0/libgstvideocrop.so
/usr/lib64/gstreamer-1.0/libgstvideofilter.so
/usr/lib64/gstreamer-1.0/libgstvideomixer.so
/usr/lib64/gstreamer-1.0/libgstvpx.so
/usr/lib64/gstreamer-1.0/libgstwavenc.so
/usr/lib64/gstreamer-1.0/libgstwavpack.so
/usr/lib64/gstreamer-1.0/libgstwavparse.so
/usr/lib64/gstreamer-1.0/libgstximagesrc.so
/usr/lib64/gstreamer-1.0/libgsty4menc.so
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gst-plugins-good/057705e31a95ff560d92f8abc2e62d2894fba796
/usr/share/package-licenses/gst-plugins-good/545f380fb332eb41236596500913ff8d582e3ead
/usr/share/package-licenses/gst-plugins-good/f6e583b41a8e91303bf19c8b17c0086872de5977

%files locales -f gst-plugins-good-1.0.lang
%defattr(-,root,root,-)

